<?php require 'templates/header.phtml' ?>
    
    <h1 class="text-center">Sign Up</h1>
    <div class="mt-5 w-25 mx-auto">
        <form method="POST" action="register">
            <div class="form-group">    
                <label for="Username">Username:</label>
                <input type="text" required class="form-control" id="username" name="Username" required><br><br>
            </div>
            <div class="form-group">
                <label for="Email">Email:</label>
                <input type="email" required class="form-control" id="email" name="Email" required><br><br>
            </div>
            <div class="form-group">
                <label for="Password">Password:</label>
                <input type="password" required class="form-control" id="password" name="Password" required><br><br>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary mt-3" value="Submit">
            </div>
        </form>
    </div>    
</body>
<?php require 'templates/footer.phtml' ?>
