<?php require_once 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./app/styles/categories.css"> 
    <link rel="stylesheet" href="./app/styles/bodyHeader.css"> 
    <title>Tienda de Juegos</title>
</head>
<body>
    <div class="container mt-5">
        <div class="text-center">
            <h1>Lista de Categorias</h1>
        </div>
        <div class="d-flex justify-content-end mt-3">
            <?php if (isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) : ?>
                <a href="formCategory" class="btn btn-primary mb-1">Agregar Categoría</a>
            <?php endif; ?>
        </div>

        <div class="row mt-3">
            <?php foreach ($categories as $key => $category) : ?>
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <?php if ($category->Cantidad_juegos > 0) : ?>
                                <h5 class="card-title">
                                    <a href="category/<?= $key + 1 ?>" class="text-decoration-none" style="font-size: 1.875rem;">
                                        <?= $category->Nombre ?>
                                    </a>
                                </h5>
                            <?php else : ?>
                                <h5 style="font-size: 1.875rem;"> <?= $category->Nombre ?> </h5>
                            <?php endif; ?>
                        </div>
                        <div class="card-body">
                            <p class="card-text fw-bold"><?= $category->Descripcion; ?></p>
                            <p class="card-text">Cantidad de juegos disponibles: <?= $category->Cantidad_juegos; ?></p>
                        </div>
                        <?php if (isset($_SESSION['USER_ID']) && isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) : ?>
                            <div class="card-footer d-flex justify-content-center">
                                <a href="editCategory/<?= $category->Id_categoria . "/" . $key ?>" class="btn btn-primary me-1">Editar</a>
                                <a href="deleteCategory/<?= $category->Id_categoria ?>" class="btn btn-danger">Eliminar</a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php require_once 'footer.phtml' ?>
</body>
</html>