<?php
require_once 'header.phtml';
$item = $item[$id];
$nombresJuegos = explode(",", $item->NombresJuegos);
$imagenesJuegos = explode(",", $item->ImagenesJuegos);
?>

<h1 class="text-center"><?= $item->Nombre ?></h1>
<div class="row justify-content-center align-items-center mb-3">
    <div class=" col-md-8 text-center">
        <h6 class="text-center"><?= $item->Descripcion ?></h6>
    </div>
</div>
<h6 class="ms-3">Cantidad de juegos en esta categoría: <?= $item->Cantidad_juegos ?></h6>
<div class="container mt-4">
    <h5 class="text-center">Lista de juegos: </h5>
    <ul>
        <div class="row">
            <?php foreach ($nombresJuegos as $key => $nombreJuego) : ?>
                <div class="col-md-4 col-sm-6 mb-4">
                    <div class="card" style="width: 100%;">
                        <img src="<?= $imagenesJuegos[$key] ?>" class="card-img-top" alt="Imagen del producto" style="max-height: 165px;">
                        <div class="card-body text-center">
                            <h4 class="card-title"><?= $nombreJuego ?></h4>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </ul>
</div>