<?php require_once 'header.phtml' ?>

<h1><?= $games[0]->nombreCategoria ?></h1>
<p class="fw-bold"><?= $games[0]->descCategoria; ?></p>
<p>Cantidad de juegos disponibles: <?= $games[0]->cantidadJuegos; ?></p>

<div class="container mt-4">
    <h5 class="text-center">Lista de juegos: </h5>
    <ul>
        <div class="row">
            <?php foreach ($games as $key => $game) : ?>
                <div class="col-md-4 col-sm-6 mb-4">
                    <div class="card" style="width: 100%;">
                        <img src="<?= $game->Imagen ?>" class="card-img-top" alt="Imagen del producto" style="max-height: 165px;">
                        <div class="card-body text-center">
                            <h4 class="card-title"><?= $game->Nombre ?></h4>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </ul>
</div>

<?php require_once 'footer.phtml' ?>