<?php require_once 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="./app/styles/categories.css">
    <link rel="stylesheet" href="./app/styles/bodyHeader.css">
    <title>Tienda de Juegos</title>
</head>

<body>
    <div class="d-flex justify-content-between align-items-center mx-3">
        <div class="text-center">
            <h1>Lista de Categorias</h1>
        </div>
        <?php if ((isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) || (isset($_SESSION['USER_IS_SUPERADMIN']) && $_SESSION['USER_IS_SUPERADMIN'])) : ?>
            <a href="formCategory" class="btn btn-primary mb-1">Agregar Categoría</a>
        <?php endif; ?>
    </div>
    <div class="container mt-5">
        <div class="row mt-3">
            <?php foreach ($categories as $key => $category) : ?>
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <?php if ($category->Cantidad_juegos > 0) : ?>
                                <h5 class="card-title">
                                    <a href="category/<?= $key + 1 ?>" class="text-decoration-none" style="font-size: 1.875rem;">
                                        <?= $category->Nombre ?>
                                    </a>
                                </h5>
                            <?php else : ?>
                                <h5 style="font-size: 1.875rem;"> <?= $category->Nombre ?> </h5>
                            <?php endif; ?>
                        </div>
                        <div class="card-body">
                            <?php if (strlen($category->Descripcion) <= 140) : ?>
                                <p class="card-text fw-bold"><?= $category->Descripcion ?></p>
                            <?php else : ?>
                                <p class="card-text fw-bold"><?= substr($category->Descripcion, 0, 140) . '...' ?></p>
                            <?php endif; ?>
                            <p class="card-text">Cantidad de juegos disponibles: <?= $category->Cantidad_juegos; ?></p>
                        </div>
                        <?php if (isset($_SESSION['USER_ID']) && ((isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) || (isset($_SESSION['USER_IS_SUPERADMIN']) && $_SESSION['USER_IS_SUPERADMIN']))) : ?>
                            <div class="card-footer d-flex justify-content-center">
                                <a href="editCategory/<?= $category->Id_categoria . "/" . $key ?>" class="btn btn-primary me-1">Editar</a>
                                <a href="deleteCategory/<?= $category->Id_categoria ?>" class="btn btn-danger">Eliminar</a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php require_once 'footer.phtml' ?>