<?php require_once 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./app/styles/bodyHeader.css">
    <link rel="stylesheet" href="./app/styles/categories.css"> 
</head>

<div class="container mt-4">
    <h1 class="titulo"><?= $games[0]->nombreCategoria ?></h1>
    <p class="fw-bold"><?= $games[0]->descCategoria; ?></p>

    <h5 class="subtitulo text-center">Lista de juegos ( <?= $games[0]->cantidadJuegos; ?> ): </h5>
    <div class="row">
        <?php foreach ($games as $key => $game) : ?>
            <div class="col-md-4 col-sm-6 mb-4">
                <div class="card" style="width: 100%;">
                    <img src="<?= $game->Imagen ?>" class="card-img-top" alt="Imagen del producto" style="max-height: 165px;">
                    <div class="card-body text-center">
                        <h4 class="card-title"><?= $game->Nombre ?></h4>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<?php require_once 'footer.phtml' ?>