<?php require_once 'header.phtml' ?>

<div class="d-flex justify-content-between align-items-center mx-2">
    <div>
        <h1>Lista de Categorias</h1>
    </div>
    <?php if (isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) : ?>
        <div>
            <a href="formCategory" type="button" class="btn btn-primary mb-1">addCategory</a>
        </div>
    <?php endif; ?>
</div>
<?php foreach ($categories as $key => $category) : ?>
    <div class="card my-2">
        <div class="card-header">
            <?php if ($category->Cantidad_juegos > 0) : ?>
                <h5 class="card-title">
                    <a href="category/<?= $key + 1 ?>" style="text-decoration: none; font-size: 30px;">
                        <?= $category->Nombre ?>
                    </a>
                </h5>
            <?php else : ?>
                <h5 style="text-decoration: none; font-size: 30px;"> <?= $category->Nombre ?> </h5>
            <?php endif; ?>
        </div>
        <div class="d-flex justify-content-between">
            <div class="card-body">
                <p class="card-text fw-bold"><?= $category->Descripcion; ?></p>
                <p class="card-text">Cantidad de juegos disponibles: <?= $category->Cantidad_juegos; ?></p>
            </div>
            <?php if (isset($_SESSION['USER_ID'])) : ?>
                <?php if (isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) : ?>
                    <div class="d-flex flex-column align-items-center justify-content-center me-3">
                        <a href="editCategory/<?= $category->Id_categoria . "/" . $key ?>" type="button" class="btn btn-primary mb-1">Edit</a>
                        <a href="deleteCategory/<?= $category->Id_categoria ?>?>" type="button" class="btn btn-danger mt-1">Delete</a>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>

<?php require_once 'footer.phtml' ?>