    <!-- main footer generico -->
    <footer class="d-flex flex-wrap justify-content-center align items-center py-3 my-4 border-top">
        <div class="align-items-center">
            <span class="text-muted">2023 TUDAI, UNICEN</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>

    </html>
