<?php require_once 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./app/styles/bodyHeader.css">
    <link rel="stylesheet" href="./app/styles/formStyle.css">
</head>

<div class="container">
    <h1><?= $mode === 'add' ? 'Agregar' : 'Editar'; ?> Juego</h1>
    <form action="<?= $mode === 'add' ? "addGame" : "editGame/" . $id ?>" method="POST">
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre del Juego</label>
            <input type="text" class="form-control" id="nombre" name="nombre" required value="<?= $mode === 'edit' ? $game[$key]->Nombre : "" ?>">
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción del Juego</label>
            <textarea class="form-control" id="descripcion" name="descripcion" required><?= $mode === 'edit' ? $game[$key]->Descripcion : "" ?></textarea>
        </div>
        <div class="mb-3">
            <label for="precio" class="form-label">Precio del Juego</label>
            <input type="number" class="form-control" id="precio" name="precio" required value="<?= $mode === 'edit' ? $game[$key]->Precio : "" ?>">
        </div>
        <?php if ($mode === 'edit') : ?>
            <div class="mb-3">
                <label for="descuento" class="form-label">Descuento</label>
                <input type="number" class="form-control" id="descuento" name="descuento" required value="<?= $mode === 'edit' ? $game[$key]->Descuento : "" ?>">
            </div>
        <?php endif; ?>
        <div class="mb-3">
            <label for="categoria" class="form-label">Categoría del Juego</label>
            <select class="form-select" id="categoria" name="categoria" required>
                <option value="" selected disabled>Elegir Categoría</option>
                <?php foreach ($categories as $category) : ?>
                    <?php if ($category->Id_categoria === $game[$key]->Id_categoria) : ?>
                        <option value="<?= $category->Id_categoria ?>" selected><?= $category->Nombre ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php foreach ($categories as $category) : ?>
                    <?php if ($category->Id_categoria !== $game[$key]->Id_categoria) : ?>
                        <option value=" <?= $category->Id_categoria ?>"><?= $category->Nombre ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="mb-3 d-flex align-items-center">
            <div class="w-75 me-3">
                <label for="imagen" class="form-label">Imagen del Juego (LINK)</label>
                <input type="text" class="form-control" id="imagen" name="imagen" value="<?= $mode === 'edit' ? $game[$key]->Imagen : "" ?>">
            </div>
            <?php if ($mode === 'edit') : ?>
                <div>
                    <p class="mb-0">Imagen actual:</p>
                    <img src="<?= $game[$key]->Imagen ?>" alt="" style="max-width: 150px;">
                </div>
            <?php endif; ?>
        </div>
        <button type="submit" class="btn btn-primary"><?= $mode === 'add' ? 'Agregar' : 'Editar'; ?> Juego</button>
    </form>
</div>