<?php require_once 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./app/styles/bodyHeader.css">
    <link rel="stylesheet" href="./app/styles/formStyle.css">
</head>

<div class="container">
    <h1><?= $mode === 'add' ? 'Agregar' : 'Editar'; ?> Categoría de Juego</h1>
    <form action="<?= $mode === 'add' ? 'addCategory' : 'editCategory/' . $id ?>" method="POST">
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre de la Categoría</label>
            <input type="text" class="form-control" id="nombre" name="nombre" required value="<?= $mode === 'edit' ? $category[$key]->Nombre : "" ?>">
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción de la Categoría</label>
            <textarea class="form-control" id="descripcion" name="descripcion" rows="4" required><?= $mode === 'edit' ? $category[$key]->Descripcion : "" ?></textarea>
        </div>
        <button type="submit" class="btn btn-primary">
            <?= $mode === 'add' ? 'Agregar' : 'Editar' ?> Categoría
        </button>
    </form>
</div>