<?php require_once 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="./app/styles/bodyHeader.css">
    <link rel="stylesheet" href="./app/styles/listGames.css">
    <title>Tienda de Juegos</title>
</head>

<body>
    <div class="d-flex align-items-center justify-content-between mx-4">
        <div>
            <h1>Lista de Juegos</h1>
        </div>
        <?php if ((isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) || (isset($_SESSION['USER_IS_SUPERADMIN']) && $_SESSION['USER_IS_SUPERADMIN'])) : ?>
            <div>
                <a href="formGame" type="button" class="btn btn-primary mb-1">Agregar Juego</a>
            </div>
        <?php endif; ?>
    </div>
    <div>
        <div class="row mt-4 mx-2">
            <?php foreach ($games as $key => $game) : ?>
                <div class="col-md-3 mb-4">
                    <div class="card juego h-100">
                        <div>
                            <img src="<?= $game->Imagen ?>" alt="<?= $game->Nombre ?>" class="card-img-top img-fluid" style="max-height: 122px;">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="game/<?= $key ?>" style="text-decoration: none; font-size: 16px;">
                                    <?= $game->Nombre ?>
                                </a>
                            </h5>
                            <p class="card-text">Precio: $<?= $game->Precio; ?></p>
                            <p class="card-text">Categoría: <?= $game->Categoria; ?></p>
                        </div>
                        <?php if (isset($_SESSION['USER_ID']) && ((isset($_SESSION['USER_IS_ADMIN']) && $_SESSION['USER_IS_ADMIN']) || (isset($_SESSION['USER_IS_SUPERADMIN']) && $_SESSION['USER_IS_SUPERADMIN']))) : ?>
                            <div class="d-flex justify-content-center">
                                <div class="text-center">
                                    <a href="editGame/<?= $game->Id_juego . "/" . $key ?>" type="button" class="btn btn-primary btn-sm">Editar</a>
                                    <a href="deleteGame/<?= $game->Id_juego ?>" type="button" class="btn btn-danger btn-sm">Eliminar</a>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php require_once 'footer.phtml' ?>