<?php require_once 'header.phtml' ?>

<div class="container mt-5">
    <div class="d-flex justify-content-center">
        <div class="card" style="width: 20rem;">
            <img src="<?= $item[$id]->Imagen ?>" class="card-img-top" alt="Imagen del producto" style="max-height: 350px;">
            <div class="card-body text-center">
                <h2 class="card-title"><?= $item[$id]->Nombre ?></h2>
                <p class="card-text">Categoría: <?= $item[$id]->Categoria ?></p>
                <p class="card-text">$<?= $item[$id]->Precio ?></p>
            </div>
        </div>
    </div>
</div>