<?php require_once 'header.phtml' ?>

<div class="container">
    <h2>Lista de Usuarios</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Rol Actual</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) : ?>
                <tr>
                    <?php if (!$user->SuperAdmin && !$user->EsAdmin) : ?>
                        <td><?= $user->Username ?></td>
                        <td>Usuario</td>
                        <td><a href="makeToAdmin/<?= $user->Id_usuario ?>" class='btn btn-primary'>Hacer Admin</a></td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>