<?php require_once 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="./app/styles/bodyHeader.css"> 
  <link rel="stylesheet" href="./app/styles/listUsers.css"> 
  <title>Tienda de Juegos</title>
</head>

<div class="container">
    <h2 class="text-center">Lista de Usuarios</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Rol Actual</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) : ?>
                <tr>
                    <?php if (!$user->SuperAdmin && !$user->EsAdmin) : ?>
                        <td><?= $user->Username ?></td>
                        <td>Usuario</td>
                        <td><a href="makeToAdmin/<?= $user->Id_usuario ?>" class='btn btn-primary'>Hacer Admin</a></td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>