<?php require 'header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <h1 class="text-center">Login</h1>
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" required class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary mt-3">Entrar</button>

        <div class="d-flex align-items-center">
            <p class="mb-0 me-2">No tienes cuenta?</p>
            <a class="btn btn-primary" aria-current="page" href="register">Register</a>
        </div>
    </form>
</div>

<? require 'footer.phtml' ?>