<?php require 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="./app/styles/bodyHeader.css"> 
  <link rel="stylesheet" href="./app/styles/formStyle.css"> 
  <title>Tienda de Juegos</title>
</head>

<div class="mt-5 w-25 mx-auto">
    <h1 class="text-center">Login</h1>
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" required class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <div class="d-flex align-items-center justify-content-between mt-3">
            <button type="submit" class="btn btn-primary">Entrar</button>
            <div class="d-flex align-items-center">
                <p class="mb-0 me-2">No tienes cuenta?</p>
                <a class="btn btn-primary" aria-current="page" href="register">Register</a>
            </div>
        </div>
    </form>
</div>

<? require 'footer.phtml' ?>