<?php require 'header.phtml' ?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="./app/styles/bodyHeader.css"> 
  <link rel="stylesheet" href="./app/styles/formStyle.css"> 
  <title>Tienda de Juegos</title>
</head>

<div class="mt-5 w-25 mx-auto">
    <h1 class="text-center">Register</h1>
    <form method="POST" action="userRegister">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" required class="form-control" id="email" name="Email">
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" required class="form-control" id="username" name="Username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="Password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<? require 'footer.phtml' ?>